### ISSUE TITLE
Поправить линтинг тестов

### ISSUE THREAD

**Issue by birthdaysgift** [week-password/wlss-backend#19]
Во время работы над настройкой окружения для юнит-тестов (#13), мы добавили линтинг кода тестов в рафф для локальной разработки. Т.е. добавили папку `tests` в команду запуска раффа в `README.md`:

> 2. Ruff.
> ```bash
> ruff check src tests
> ```

Но при этом забыли обновить команду в `envs/ci/docker-compose.yml`:
```yml
ruff:
  <<: *app-build
  entrypoint: ruff check src
```

***

Похожая ситуация произошла и с пайлинтом, но пайлинт мы забыли обновить не только в `envs/ci/docker-compose.yml`, но и в `README.md`.

В рамках этой задачи необходимо добавить папку `tests` в команду запуска раффа и пайлинта на CI в файле `envs/ci/docker-compose.yml`. А также добавить папку `tests` в команду запуска пайлинта в `README.md`.

**Comment by birthdaysgift** [comment]
К сожалению ни рафф, ни пайлинт не позволяют через конфиг настроить директории, на которых они должны прогоняться, поэтому приходится вписывать это непосредственно в команду вызова. Настройка этого параметра через конфиг была бы очень удобной и позволила бы избежать подобных ошибок, описанных в этом тикете.

Рафф и пайлинт - минус балл каждому.

Чтобы не страдать при поддержании этого дублирования, можно инкапсулировать передачу директорий для линтинга в баш скрипт, например для раффа:
```bash
#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

ruff check "$@" src tests
```

***

Остаётся только решить вопрос, где эти скрипты должны лежать.

- Мы не можем положить их в `envs/`, т.к. они не привязаны к конкретному окружению, и могут выполняться на разных окружениях - при локальной разработке, на CI и пр. 
- Класть их в корневую директорию тоже не очень хочется, т.к. на данный момент она содержит только файлы конфигурации. С другой стороны мы создали эти два скрипта, чтобы так сказать "расширить возможности конфигурации" пайлинта и раффа, но тем не менее эти файлы всё равно по факту являются скриптами запуска.
- скорее всего придётся положить их в корень проекта в папку `run`, тогда они не будут мешаться с конфигурациями в корне, и при это путь до вызова этих тулов будет довольно небольшим и это будет удобно писать в терминале, типа
  `$ run/pylint`
  `$ run/ruff`
  правда название `run` не очень хорошо отражает назначение содержимого этой папки...

**Comment by Rey-Lane** [comment]
Пока что передача директорий через скрипт выглядит излишней. Как говорила одна великая разработчица "Это оверинжиниринг". Хотя, один раз мы уже обожглись на этом, надо будет подумать. Но делать это надо, во всяком случае, не в рамках этого тикета.

**Comment by birthdaysgift** [comment]
> один раз мы уже обожглись на этом

Для меня это не один, а два раза. Потому что я сначала заметил косяк с раффом и создал под это тикет. Подумал, что всё учел и только через пару часов понял, что там ещё и с пайлинтом такая же шляпа, пришлось переквалифицировать тикет. Так что считай два раза обжёгся.

К тому же когда мы начнём писать код и запускать линтеры, то мы довольно быстро устанем писать длинные команды, типа:
```bash
pylint src tests
ruff check src tests
```

И кажется этим будет пользоваться чуть проще:
```bash
run/pylint
run/ruff
```

Но вообще меня больше беспокоит проблема дублирования.


> Но делать это надо, во всяком случае, не в рамках этого тикета.

Да, конечно, это будет в отдельном тикете.
